### ISSUE TITLE
Implementing backend search with Angular.js

### ISSUE THREAD

**Issue by cmgchess** [algolia/algoliasearch-helper-js#884]
Hello 👋

I found out Instantsearch.js supports backend search [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/js/)
Since I'm using Angular.js and Instantsearch doesn't support Angular.js I would like to know if it is possible to perform backend search by defining a custom search client in the helper library with Angular.js

Thanks.

**Comment by Haroenv** [comment]
Hi @cmgchess, do you mean Angular.js, the framework that has reached EOL?

Any way, you can pass a different value than the `algoliasearch` client in the helper too, following pretty much the same guide as https://www.algolia.com/doc/guides/building-search-ui/going-further/backend-search/in-depth/backend-instantsearch/js/#searching-for-results

If you try this out and get stuck somewhere, feel free to comment with reproduction.

**Comment by cmgchess** [comment]
thanks for the reply!

I tried this out a little but I can't seem to populate the components. I'm sending requests and getting back correct responses as seen from the networks tab.

I have attached codepen demo for reference
https://codepen.io/cmgchess/pen/QWqYWVN

**Comment by Haroenv** [comment]
That's because the example you went with still used the callback-based version (only?) of the search client, not the promise version: https://codepen.io/Haroenv/pen/JjrxMaq

if I remember it correctly this was changed/fixed in newer versions of algoliasearch-helper

**Comment by cmgchess** [comment]
In https://codepen.io/Haroenv/pen/JjrxMaq when I pass the `customSearchClient` even with the callback it still doesn't seem to work 🤔

**Comment by cmgchess** [comment]
@Haroenv  I checked with version 2.58.1 (latest version in cdnjs) and the callback version worked 
https://codepen.io/cmgchess/pen/oNGmqWE

Thanks for helping me out
